name: Deploy ego1st.cn

on:
  push:
    branches: [dev]
jobs:
  deploy:
    name: Deploy ego1st.cn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "18"
          cache: "yarn"
      - name: Build website
        run: |
          yarn
          yarn build
      - name: Deploy ego1st.cn
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            publish_branch: prod
            user_name: EGo1ST
            user_email: 974412906@qq.com
