name: ego1st deployment

on:
  pull_request:
    branches: [prod]

jobs:
  test-deploy:
    name: ego1st deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: ego1st build
        run: |
          yarn install --frozen-lockfile
          yarn build
