name: Deploy ego1st blog

on:
  push:
    branches: [dev]

jobs:
  deploy:
    name: Deploy ego1st blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Build website
        working-directory: website
        run: |
          yarn install --frozen-lockfile
          yarn build